site_name: World War Online
site_url: https://guides.worldwaronline.com/
edit_uri: https://github.com/Chilltime/mkdocs-worldwaronline/edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/regular/comment-dots
    repo: fontawesome/brands/github
  favicon: favicon.ico
  features:
    - content.action.edit
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking
    - toc.follow
    # - navigation.tabs
    # - navigation.top
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - privacy
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      repository: chilltime/mkdocs-worldwaronline
      branch: main

copyright: |
  Copyright &copy; 2025 Chilltime, Lda.
